[project]
name = "slurm-rave"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "questionary>=2.1.1",
]
